name: Restrict PRs to main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        run: |
          echo "PR opened from: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "❌ Pull requests to main are only allowed from dev."
            exit 1
          fi
